package cn.itsite.jbase.mapper;


import cn.itsite.jbase.entity.DictItem;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface DictItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated Wed Nov 28 18:17:21 CST 2018
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated Wed Nov 28 18:17:21 CST 2018
     */
    int insert(DictItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated Wed Nov 28 18:17:21 CST 2018
     */
    DictItem selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated Wed Nov 28 18:17:21 CST 2018
     */
    List<DictItem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated Wed Nov 28 18:17:21 CST 2018
     */
    int updateByPrimaryKey(DictItem record);
}