package cn.itsite.jbase.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class DictItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_item.uid
     *
     * @mbggenerated Wed Nov 28 18:17:21 CST 2018
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_item.type_uid
     *
     * @mbggenerated Wed Nov 28 18:17:21 CST 2018
     */
    private String typeUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_item.code
     *
     * @mbggenerated Wed Nov 28 18:17:21 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_item.name
     *
     * @mbggenerated Wed Nov 28 18:17:21 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_item.enable
     *
     * @mbggenerated Wed Nov 28 18:17:21 CST 2018
     */
    private Boolean enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_item.create_time
     *
     * @mbggenerated Wed Nov 28 18:17:21 CST 2018
     */
    @JsonFormat(pattern = "yyyy-MM-dd hh:mm:ss a", locale = "zh", timezone = "GMT+8")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_item.update_time
     *
     * @mbggenerated Wed Nov 28 18:17:21 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_item.uid
     *
     * @return the value of dict_item.uid
     * @mbggenerated Wed Nov 28 18:17:21 CST 2018
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_item.uid
     *
     * @param uid the value for dict_item.uid
     * @mbggenerated Wed Nov 28 18:17:21 CST 2018
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_item.type_uid
     *
     * @return the value of dict_item.type_uid
     * @mbggenerated Wed Nov 28 18:17:21 CST 2018
     */
    public String getTypeUid() {
        return typeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_item.type_uid
     *
     * @param typeUid the value for dict_item.type_uid
     * @mbggenerated Wed Nov 28 18:17:21 CST 2018
     */
    public void setTypeUid(String typeUid) {
        this.typeUid = typeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_item.code
     *
     * @return the value of dict_item.code
     * @mbggenerated Wed Nov 28 18:17:21 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_item.code
     *
     * @param code the value for dict_item.code
     * @mbggenerated Wed Nov 28 18:17:21 CST 2018
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_item.name
     *
     * @return the value of dict_item.name
     * @mbggenerated Wed Nov 28 18:17:21 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_item.name
     *
     * @param name the value for dict_item.name
     * @mbggenerated Wed Nov 28 18:17:21 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_item.enable
     *
     * @return the value of dict_item.enable
     * @mbggenerated Wed Nov 28 18:17:21 CST 2018
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_item.enable
     *
     * @param enable the value for dict_item.enable
     * @mbggenerated Wed Nov 28 18:17:21 CST 2018
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_item.create_time
     *
     * @return the value of dict_item.create_time
     * @mbggenerated Wed Nov 28 18:17:21 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_item.create_time
     *
     * @param createTime the value for dict_item.create_time
     * @mbggenerated Wed Nov 28 18:17:21 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_item.update_time
     *
     * @return the value of dict_item.update_time
     * @mbggenerated Wed Nov 28 18:17:21 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_item.update_time
     *
     * @param updateTime the value for dict_item.update_time
     * @mbggenerated Wed Nov 28 18:17:21 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        return "DictItem{" +
                "uid='" + uid + '\'' +
                ", typeUid='" + typeUid + '\'' +
                ", code='" + code + '\'' +
                ", name='" + name + '\'' +
                ", enable=" + enable +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                '}';
    }
}